gitRepoId: onfido-node
npmName: "@onfido/api"
npmRepository: github:onfido/onfido-node
npmVersion: ${CLIENT_LIBRARY_VERSION}
enumUnknownDefaultCase: true
supportsES6: true
withNodeImports: true
legacyDiscriminatorBehavior: false
files:
  LICENSE.mustache:
    destinationFilename: LICENSE
  webhook-event-verifier.mustache:
    destinationFilename: webhook-event-verifier.ts
