inputSpec: openapi.yaml
gitUserId: onfido
generatorName: ${GENERATOR_NAME}
library: "${GENERATOR_LIBRARY}"
templateDir: generators/${GENERATOR}/templates
outputDir: generated/artifacts/${GENERATOR}
disallowAdditionalPropertiesIfNotPresent: false
enumUnknownDefaultCase: true
removeEnumValuePrefix: true
additionalProperties:
  apiVersion: v3.6
  documentationUrl: https://documentation.onfido.com
  supportUrl: https://public.support.onfido.com/
  supportDescription: Customer Experience Portal
